---
title: "Exericio - Tratamento de dados"
output: html_notebook
---


```{r}
dados_tempo = read.csv("tempo.csv", sep=";",na.strings = "", stringsAsFactors = T) #os valores ausentes sao strings vazias e converte em fatores ao ler os dados, pois facilita análises que se beneficiam de representação de análises categoricas como fatores

head(dados_tempo) #vemos as primeiras linhas e colunas dos nossos dados
summary(dados_tempo)

```
Explorar dados, colunas categóricas
```{r}
counts= table(dados_tempo$Aparencia)
barplot(counts, main="Aparencia", xlab = "Aparencia") #percebe-se que ha um fora do padrao que é a aparencia "menos"

counts= table(dados_tempo$Jogar)
barplot(counts, main="Jogar", xlab = "Jogar") #normal

counts = table(dados_tempo$Vento)
barplot(counts, main = "Vento", xlab = "Vento")
```
Explorar colunas numericas
```{r}
summary(dados_tempo$Temperatura) #há um erro de temperatura maxima 
boxplot(dados_tempo$Temperatura)
hist(dados_tempo$Temperatura)
```
Umidade
```{r}
summary(dados_tempo$Umidade) #há NA's
boxplot(dados_tempo$Umidade)
hist(dados_tempo$Umidade) #percebe-se que ultrapassou umidade maxima do domínio
```
Verificar NA's
```{r}
dados_tempo[!complete.cases(dados_tempo),] #identificar e selecionar as linhas que contenham valores ausentes (NA) em pelo menos uma das suas colunas.

#identificamos em umidade e vento
```
Tratar aparencia
```{r}
unique(dados_tempo$Aparencia)
summary(dados_tempo$Aparencia)
dados_tempo[!dados_tempo$Aparencia %in% c("chuva","nublado","sol"),]$Aparencia = "sol"
summary(dados_tempo$Aparencia)
#remover fatores nao usados
dados_tempo$Aparencia = factor(dados_tempo$Aparencia)
summary(dados_tempo$Aparencia)
```
Tratar Umidade
```{r}
summary(dados_tempo$Umidade)
median(dados_tempo$Umidade, na.rm = T) #media é 85
dados_tempo[is.na(dados_tempo$Umidade) ,]$Umidade = median(dados_tempo$Umidade, na.rm = T)
dados_tempo[!complete.cases(dados_tempo$Umidade), ] #tratamos as NA's colocando a media da umidade

#ver fora do dominio
dados_tempo[dados_tempo$Umidade < 0 | dados_tempo$Umidade > 100 ,]$Umidade #valor 200 fora do dominio
dados_tempo[dados_tempo$Umidade < 0 | dados_tempo$Umidade > 100 ,]$Umidade = median(dados_tempo$Umidade, na.rm = T) 

dados_tempo[dados_tempo$Umidade < 0 | dados_tempo$Umidade > 100 ,] #reverificamos 
summary(dados_tempo$Umidade)
```
```{r}
summary(dados_tempo$Temperatura)
median(dados_tempo$Temperatura, na.rm=T) #media 73.5
dados_tempo[dados_tempo$Temperatura < -130 | dados_tempo$Temperatura > 130 ,]$Temperatura = median(dados_tempo$Temperatura, na.rm=T)
dados_tempo[dados_tempo$Temperatura < -130 | dados_tempo$Temperatura > 130 ,]

summary(dados_tempo$Temperatura)
```
Nao precisa tratar o "Jogar" pois está aparentemente correto
```{r}
summary(dados_tempo$Vento) #tem mais FALSO do que VERDADEIRO
dados_tempo[is.na(dados_tempo$Vento), ]
dados_tempo[is.na(dados_tempo$Vento), ]$Vento = 'FALSO'
dados_tempo[is.na(dados_tempo$Vento), ]
summary(dados_tempo$Vento)
```
